# Generated by Django 6.0.2 on 2026-02-20 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.URLField(max_length=500)),
                ('type', models.CharField(choices=[('quick', 'Quick Scan'), ('deep', 'Deep Scan')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('progress', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('scan_duration', models.DurationField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], max_length=10)),
                ('file', models.FileField(upload_to='reports/')),
                ('format', models.CharField(choices=[('executive', 'Executive Summary'), ('detailed', 'Detailed Report'), ('technical', 'Technical Report'), ('compliance', 'Compliance Report')], default='detailed', max_length=20)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('include_remediation', models.BooleanField(default=True)),
                ('include_evidence', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='base.scan')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target', models.URLField(max_length=500)),
                ('scan_type', models.CharField(choices=[('quick', 'Quick Scan'), ('deep', 'Deep Scan')], max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=10)),
                ('next_run', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('cron_expression', models.CharField(blank=True, max_length=100)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('threat_type', models.CharField(choices=[('cve', 'CVE'), ('exploit', 'Exploit'), ('malware', 'Malware'), ('phishing', 'Phishing'), ('ransomware', 'Ransomware'), ('zero_day', 'Zero Day'), ('apt', 'APT')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('affected_software', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField()),
                ('reference_urls', models.JSONField(default=list)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('confirmed', 'Confirmed')], default='medium', max_length=20)),
                ('cve_id', models.CharField(blank=True, max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=100)),
                ('affected_versions', models.JSONField(default=list)),
                ('patches_available', models.BooleanField(default=False)),
                ('patch_urls', models.JSONField(default=list)),
                ('exploit_available', models.BooleanField(default=False)),
                ('exploit_urls', models.JSONField(default=list)),
                ('mitigation_steps', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['threat_type'], name='base_threat_threat__a4d364_idx'), models.Index(fields=['severity'], name='base_threat_severit_2b05bb_idx'), models.Index(fields=['-published_date'], name='base_threat_publish_92599b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=10)),
                ('description', models.TextField()),
                ('remediation', models.TextField(blank=True)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('cve_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('accepted', 'Accepted Risk')], default='open', max_length=15)),
                ('affected_component', models.CharField(blank=True, max_length=255)),
                ('proof_of_concept', models.TextField(blank=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='base.scan')),
            ],
            options={
                'ordering': ['-severity', '-cvss_score'],
            },
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['status'], name='base_scan_status_7da4a5_idx'),
        ),
        migrations.AddIndex(
            model_name='scan',
            index=models.Index(fields=['created_by', '-start_time'], name='base_scan_created_6be899_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['severity'], name='base_vulner_severit_5459cd_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['status'], name='base_vulner_status_11fba2_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnerability',
            index=models.Index(fields=['scan', 'severity'], name='base_vulner_scan_id_a898a1_idx'),
        ),
    ]
