# Generated by Django 6.0.2 on 2026-02-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
