# Generated by Django 6.0.2 on 2026-02-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_vulnerability_cwe_id_vulnerability_evidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepScanCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_remaining', models.IntegerField(default=0)),
                ('total_credits_purchased', models.IntegerField(default=0)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('subscription_tier', models.CharField(default='free', max_length=50)),
                ('subscription_expires', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_credits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeepScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('target', models.URLField(blank=True, max_length=500)),
                ('data', models.JSONField()),
                ('har_file', models.FileField(blank=True, null=True, upload_to='deep_sessions/har/')),
                ('dom_snapshots', models.JSONField(blank=True, default=list)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('request_count', models.IntegerField(default=0)),
                ('unique_urls', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('findings_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('ai_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_analysis_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deep_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeepFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('business_logic', 'Business Logic Flaw'), ('authentication', 'Authentication Issue'), ('authorization', 'Authorization Flaw'), ('xss', 'Cross-Site Scripting'), ('sqli', 'SQL Injection'), ('idor', 'Insecure Direct Object Reference'), ('session', 'Session Management'), ('api', 'API Security'), ('race_condition', 'Race Condition'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2000)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('parameter', models.CharField(blank=True, max_length=255)),
                ('request_id', models.IntegerField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='deep_screenshots/')),
                ('har_snippet', models.JSONField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('fixed', 'Fixed'), ('false_positive', 'False Positive'), ('accepted', 'Accepted Risk')], default='open', max_length=20)),
                ('is_false_positive', models.BooleanField(default=False)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='base.deepscansession')),
            ],
            options={
                'ordering': ['-severity', '-cvss_score'],
            },
        ),
        migrations.AddIndex(
            model_name='deepscansession',
            index=models.Index(fields=['user', '-created_at'], name='base_deepsc_user_id_e96c98_idx'),
        ),
        migrations.AddIndex(
            model_name='deepscansession',
            index=models.Index(fields=['status'], name='base_deepsc_status_402d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='deepscansession',
            index=models.Index(fields=['session_id'], name='base_deepsc_session_20f832_idx'),
        ),
        migrations.AddIndex(
            model_name='deepfinding',
            index=models.Index(fields=['session', 'severity'], name='base_deepfi_session_bcded4_idx'),
        ),
        migrations.AddIndex(
            model_name='deepfinding',
            index=models.Index(fields=['finding_type'], name='base_deepfi_finding_ace6bb_idx'),
        ),
    ]
