# Generated by Django 6.0.2 on 2026-03-01 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_deepscancredit_deepscansession_deepfinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=8)),
                ('permissions', models.CharField(choices=[('read', 'Read Only'), ('read_write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('use_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='base_apikey_user_id_efcece_idx'), models.Index(fields=['key'], name='base_apikey_key_b381d3_idx'), models.Index(fields=['prefix'], name='base_apikey_prefix_e70cac_idx')],
            },
        ),
    ]
