# Generated by Django 6.0.2 on 2026-04-11 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_notificationsetting_organization_scandefault_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('full_target', models.URLField(max_length=500)),
                ('verification_method', models.CharField(choices=[('dns_txt', 'DNS TXT Record'), ('file', 'Verification File'), ('meta_tag', 'HTML Meta Tag')], default='dns_txt', max_length=20)),
                ('verification_token', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('failed', 'Verification Failed'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('authorization_document', models.FileField(blank=True, null=True, upload_to='auth_docs/')),
                ('authorization_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField(default=0)),
                ('last_verification_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='ScanAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('scope_confirmed', models.BooleanField(default=True)),
                ('authorized_target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scans', to='base.authorizedtarget')),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authorization', to='base.scan')),
            ],
        ),
    ]
